# Generated by Django 3.2.4 on 2021-07-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_arte_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arte',
            new_name='Deporte',
        ),
    ]
